### ISSUE TITLE
Regex is not allowing me to type

### ISSUE THREAD

**Issue by sebaplaza** [AlphaGit/ng-pattern-restrict#15]
I'm testing a regex of this type:
    `<input type="text" ng-pattern-restrict="^\d{9}\s{1}\d{5}$"/>`

Normally, it matches with 321456789 45687, but i can't input text.

**Comment by AlphaGit** [comment]
It probably is not matching partial entries, so until you are done entering the whole expression, the intermediate values that you're entering are not actually validating against the expression.

Try this regex and see if this solves your problem: `^\d{0,9]\s?\d{0,5}$^.

**Comment by sebaplaza** [comment]
Still not working.
By the way, the default example "^[0-9]*$" is working perfectly.

**Comment by AlphaGit** [comment]
Ok, I'll give it a try later on and get back to you.

**Comment by AlphaGit** [comment]
Try this one `^\d{0,9}$|^\d{9}\s?$|^\d{9}\s\d{0,5}$`. My previous one was closer but would allow for undesired results.

To validate final results on `onChange` you still need to use the common `ng-pattern`. This library is to restrict entries while typing, as a mask. This means that the regex is validated on each keystroke, so your regex needs to allow for intermediate values.

As an example, if you wanted to validate for a zip code, `^\d{5}$` is not going to work because a user won't be able to enter all 5 digits at once (except when copy-pasting). If you want to allow your users to enter partial values, you need to use something like `^\d{0,5}$`.

**Comment by AlphaGit** [comment]
@sebaplaza Have you had any luck with that regex? Did that solve the problem for you?

**Comment by sebaplaza** [comment]
Sorry i was busy all these days.

Thanks for your solution. It's working.

Anyway, how you said, the regex has to be validated with angular ng-pattern at the end, and the ng-pattern-restrict is used just to restrict the available characters, including "null".

Well, knowing how the plugin works, finally i decided to simplify my code to:

		<input 	type="text" 
				ng-pattern="/^\d{9}\s{1}\d{5}$/"
				ng-pattern-restrict="^(\d{0,9} ?\d{0,5})$"
				/>
To validate expresions of this type 999999999 99999.

It's a great plugin!

By the way, i was thinking that would be great to add a mask support, something like https://github.com/RobinHerbots/jquery.inputmask

**Comment by AlphaGit** [comment]
@sebaplaza Thank you very much for checking back. I'm glad the solution works. Please note that the simplified regex will allow a user to type "1 1", and that'll be rejected later. That's why I kind of made a dirtier one.

Again, thank you very much -- I like the idea of having mask support. I had created #16 for that. I won't be able to work on it anytime soon, but I'm of course accepting PRs. =)

**Comment by sebaplaza** [comment]
Yes, you're right ! Thanks for your feedback.

Well, i would love to help you with the project, but i'm just starting with angularjs (since a few months)
But if you need some help i'm in !

**Comment by chuckamus-prime** [comment]
this should be something you show on the main page as an example. i almost gave up until i looked here.

**Comment by AlphaGit** [comment]
@chuckamus-prime It took me forever to do it, but there it is! I added notes to the README.md file. Thanks!

**Comment by chuckamus-prime** [comment]
Thank you! That put into words exactly what I learned. Glad you added that for future users, that makes it clear.
