### ISSUE TITLE
Angular2 Support?

### ISSUE THREAD

**Issue by LMFinney** [AlphaGit/ng-pattern-restrict#32]
Do you have any plans to add Angular2 support? I know it's still under development, so I don't expect a working version now, but do you expect to update this library when Angular2 is stable?

**Comment by AlphaGit** [comment]
I think we could give it a shot. Angular2 has made drastic changes in regards to directive approach, so it may require a complete rewrite.

Still, it'll be a fun experiment to do so yes -- I'll give it a shot. =)

**Comment by LMFinney** [comment]
Good to hear. We're rewriting our app from ng1 to ng2, and it's nearly a complete rewrite, so I get that it's non-trivial. Part of it for us will be rewriting or replacing 3rd-party libs that no longer work, so it's good to hear that ng-pattern-restrict might not have to be on that list :)

Thanks

**Comment by AlphaGit** [comment]
Hi @LMFinney, just a heads up since I know you're relying on me.

I have not been able to get into Angular2 yet there are a few things to finish on my queue before I even do. I think that this could take a little bit more, I'm thinking in the range of weeks or a few months, depending on what else comes up in my personal life.

PS: I'd be really interested to see what project (if public) you're using this library in. I never took it very seriously and knowing that it is actually being used in real projects makes me really happy.

**Comment by LMFinney** [comment]
No problem - we aren't going to be freezing code on this project for many months, so we have time to wait on your or look for alternatives (or perhaps rewrite ourselves and offer a PR).

Unfortunately, it's not a public project - it's the user interface for a medical device.

**Comment by LMFinney** [comment]
I have migrated ng-pattern-restrict.js to TypeScript/Angular 2 beta.1 locally. I have requested permission from my management to contribute this new code back to you. If I get clearance, how would you like it? I haven't done a PR before, and I'm not sure you want a PR on top of the working AngularJS version, so maybe that wouldn't be the best (maybe you prefer to post it in a new fork, for example).

I'll let you know if/when I get permission, and then we can arrange how you want me to contribute the code back.

**Comment by LMFinney** [comment]
The initial response from management prohibits me from contributing back. We'll keep trying.

**Comment by AlphaGit** [comment]
Hi @LMFinney. That's great, thank you very much.

The code is distributed under MIT licensing, so companies are allowed to make efforts out of it and not share it. I really appreciate you putting up a fight in that aspect, but I understand a company may decide otherwise.

As for how to contribute it, I had created an `angular-beta` branch, and your initial PR would basically wipe out anything that I have in place and set the foundation for the new version. This will be a branch that would evolve with AngularJS until it is actually released, at which point, after a final revision and adjustment, I'd switch branches around to make the Angular2 version the official for this repository, and the Angular1+ an old version that we support.

Thanks again, I really appreciate it!

**Comment by AlphaGit** [comment]
I have created a sister project for Angular 2+ compatibility. There are certain aspects missing on that project, like the correct setup of automated testing, but the overall working of the directive is in place.

The project is [a-pattern-restrict](https://github.com/AlphaGit/a-pattern-restrict).
