### ISSUE TITLE
Allow numbers(digit with decimal point) upto 2 decimal places

### ISSUE THREAD

**Issue by Anubhav-Bhojne** [AlphaGit/ng-pattern-restrict#33]
I have the following ng-pattern /^[0-9]+(\.[0-9]{1,2})?$/ which would allow users to enter number with upto 2 decimal places. However this directive doesn't allow user to input decimal.

**Comment by AlphaGit** [comment]
Hi! I would modify the expression so that it reads ` /^[0-9]+(.[0-9]{0,2})?$/`

That is so you can support the input being "x." (x being a number), while the user is in the action of typing it.

Please see the notes on [progressive regexes](https://github.com/AlphaGit/ng-pattern-restrict#notes).

Let me know if that solved your problem. If not, I can look deeper into it.

**Comment by Anubhav-Bhojne** [comment]
I tried using the above regex. However the problem with the above regex is that,
even if a field is not mandatory, the user cant delete the last inputted character. It sticks around because of the /^[0-9]+. 
If i change /^[0-9]+ to /^[0-9]*, last character deletion works, however i see another issue where inputting only . into input fields makes the input field valid.

**Comment by AlphaGit** [comment]
You're right. The same logic applies to that section of the regex as well.

From here on out, it is all depending on how you craft the regex for the desired result.

Try this one:

`/^(?:[0-9]+(?:\.[0-9]{0,2})?)?$/`

Here's the explanation, from the outside to the inside:

`(?:[0-9]+(?:\.[0-9]{0,2})?)?` is all optional because you want to accept empty string too, in the case the user clears the input. It is also a non-capturing group.

`[0-9]+(?:\.[0-9]{0,2})?` is any non-empty sequence of digits, with the decimal part optional and non-capturing too.

`\.` is matching the period exactly.

`[0-9]{0,2}` should match the decimal part, which can be empty (if the user hasn't entered it yet) or can have up to 2 digits.

If you're having trouble with the regexes, you can always test on https://regex101.com/, which I found very simple to visualize.

**Comment by Anubhav-Bhojne** [comment]
thanks. this works

**Comment by AlphaGit** [comment]
@Anubhav-Bhojne I'm glad it did! Feel free to open up any tickets if you find any more problems.

**Comment by SandipanDutta** [comment]
Hi, this is what I was looking for for decimals..but I also want the field to be mandatory, this expression if I leave black makes the form valid, can you please help ? Thanks.

**Comment by AlphaGit** [comment]
Hi @SandipanDutta! I think the simplest approach would be to use ˋngRequiredˋ.
