### ISSUE TITLE
Filter stops working after first character is validated

### ISSUE THREAD

**Issue by JulioDeL** [AlphaGit/ng-pattern-restrict#34]
Hello,

I have installed the module via bower and added it as a dependency of my app. I have tried then the example of the documentation but it is not working as expected.

This is the HTML: 

`<input type="text" pattern="[0-9]+" ng-pattern-restrict />`

For the first typed character it gets correctly banned/added depending if it was a number or not, and successive characters are all added to the input even if they don't match the regular expression.

For instance, I first typed the number 1 and then the letter r and both were added to the input even though the pattern allow only numbers. Also I saw this message in the console log: 

`[ngPatternRestrict] New value passed validation against /[0-9]/ 1r`

Which is not right since r is not a number.

I would like to know if I'm doing something wrong or there is a bug in the module. My app uses angular 1.4.7 and I'm trying on Chrome.

Thank you.

**Comment by AlphaGit** [comment]
Hi! What you're seeing is actually correct. `1r` will match against `/[0-9]/` because it does match the first character.

To validate the whole string, you probably want to add string starting and terminator characters in your regex: `^[0-9]+$`.

Also, if you want to allow the field to start out blank, you need to allow for that too: `^[0-9]*$`.

However, I do see your point: the example given in the documentation is confusing -- it definitely will not behave in the way that a first timer to the library would expect, and that's not good. I'll make a few adjustments to it soon.

**Comment by JulioDeL** [comment]
Oops...I thought the regular expression was run against each key individually and not the whole string. I changed it and the input behaves as I desired.

Thanks for your help. I'm closing this issue.

**Comment by AlphaGit** [comment]
Not a problem! Glad to be of help. :)
