### ISSUE TITLE
How to switch off ng-pattern-restrict console log?

### ISSUE THREAD

**Issue by JulioDeL** [AlphaGit/ng-pattern-restrict#35]
Hello,

I would like to know if it is possible to switch off the logs without applying uglify. By looking at the code it seems that can be accomplished by declaring a global variable 'DEBUG' and setting it to false, but I would like to avoid declaring global variables at all cost.

Thank you

**Comment by AlphaGit** [comment]
Hi!

You can use the `DEBUG` global variable if you're using the un-minified version. This is used to automatically take out the logging instructions when generating the minified version. You'll find that the minified code does not make any calls to logs, and you wouldn't have to apply uglify (it's already done for you).

However, if you still want to use the un-minified source, the library uses `$log` ([ref](https://docs.angularjs.org/api/ng/service/$log)), so you can also:

- Inject a noop `$log` service through the `$logProvider`
- Set `$logProvider.debugEnabled` to `false`.

**Comment by JulioDeL** [comment]
Thanks for your help! I'm closing this question.

**Comment by JulioDeL** [comment]
Hello Alpha,

I thought the min version would be used in production environments and so the logs would be disabled, but that is not happening.
According to the installment instructions I added ng-pattern-restrict dependency to my bower.json file, and after executing bower install, I see both the minified and unminified versions on the bower components folder. How can I enforce the usage of the minified version to get rid of the logs?

Thank you.

**Comment by AlphaGit** [comment]
Hi @JulioDeL, there's currently no logic in this library to pick either the minified or complete version. Your build script or inclusion logic or whichever you have should pick which file you want to use in every environment.

This gives you complete flexibility as to mix it up: you can use minified everywhere, or only in PROD, you can use the original one everywhere or not. It's really up to you to decide. 

As for the inclusion logic, just reference the .min version instead of the other one. That's all that there is to it!

I hope this helps.

**Comment by JulioDeL** [comment]
It truly helped. Thanks for the explanation!
