### ISSUE TITLE
Trying to display a message when "New value did NOT pass validation against"

### ISSUE THREAD

**Issue by irlnathan** [AlphaGit/ng-pattern-restrict#39]
I'm trying to display an error message when a value doesn't pass the validation. Currently I'm using

`
<span style="color:red" ng-show="signup.username.$error.pattern">Only letters and numbers are allowed!</span>
`

However, `pattern` doesn't ever have a `truthy` value. Any ideas?

**Comment by AlphaGit** [comment]
Hi! Because of the nature of this library, when a non-matching pattern is found, the value will be replaced with the last one that actually does match. This all happens very close to the DOM so it runs before the digest phase.

This means that you'll never end up in a situation where `$error.pattern` will be truthy.

In the situation where you are, I think you may want to use the regular ng-pattern directive instead of this library.

**Comment by irlnathan** [comment]
@AlphaGit, I appreciate the info! Except for being able to display an error message, the library does exactly what I need. Thanks again.

**Comment by AlphaGit** [comment]
Thank you very much! I'm glad you're finding it useful. 

Also, I believe this discussion might as well turn into a feature. It would not be a bad idea for the directive to report back on events when a validation is successful or it is not. Maybe it would also allow you (as a consumer of the library) to intercept and do some work with the wrong value itself.

Let me think about it. If any of these is stopping you, let me know so I can get on those first.

**Comment by AlphaGit** [comment]
#41 created for me to follow this up

**Comment by irlnathan** [comment]
That would be great!
